version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=${API_URL}
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT:-5000}
      - API_URL=${API_URL}
      - MONGOOSE_DEBUG=${MONGOOSE_DEBUG:-false}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge 