name: Node.js CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'server/package.json'
    
    - name: Install dependencies
      working-directory: ./server
      run: npm ci
      
    - name: Run tests
      working-directory: ./server
      run: npm test
      env:
        CI: true
        JWT_SECRET: ${{ secrets.JWT_SECRET || 'testsecretkey' }}
        
    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: server/coverage 